# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gd7IG98KzQi1FCN81LORGQPwyWc8I5wY

CALCULADORA PROMEDIO
"""

suma = 0
contador = 0

# Usamos un ciclo do-while
while True:
    numero = float(input("Ingresa un número: "))
    suma += numero  # Acumulamos la suma
    contador += 1    # Incrementamos el contador de números

    # Preguntamos si desea ingresar otro número
    respuesta = input("¿Deseas ingresar otro número? (s/n): ").lower()

    if respuesta != "s":
        break

# Verificamos si se ingresaron números
if contador > 0:
  # se calcula el promedio
    promedio = suma / contador
    print(f"El promedio es: {promedio}")
else:
    print("No se ingresaron números.")