# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xs28h5sH-zCZXUDLn9mT2qqQcTgfxgFd

Contador de números positivos
"""

contador = 0

# Bucle while que se repetirá hasta que el número sea negativo
while True:
    numero = int(input("Ingresa un número: "))

    # Si el número es negativo, salimos del bucle
    if numero < 0:
        break
    else:
        # Si el número es positivo, incrementamos el contador
        contador += 1

# Mostramos la cantidad de números positivos ingresados
print("Cantidad de números positivos ingresados:", contador)