# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ljQGiI3abHceXHkvZ5gdT8yQNwGyxtm

Programa para calcular la suma de los números pares del 1 al 100
"""

suma = 0  # Variable para acumular la suma

# Ciclo que recorre los números del 1 al 100
for i in range(1, 101):
    # Verifica si el número es par
    if i % 2 == 0:
        suma += i  # Suma los números pares

# Muestra el resultado final del ejercicio
print("La suma de los números pares entre 1 y 100 es:", suma)